# Theme settings
doks:
    baseurl: /docs
    color_theme: red
    header:
        logo:
            text: DDoS Lab
            image:
        nav:
            - item_name: Sobre o DDoS Lab
              item_url: 'https://colab-uff.github.io/ddoslab/'
            - item_name: Sobre o coLAB
              item_url: 'https://colab-uff.github.io/'

    footer:
        content:
            logo:
                text: DDoS Lab
                image:
            copyright: Copyright &copy; 2022. - DDoS Lab <br>Todos os direitos reservados.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/ddoslab1'
            - network_name: instagram
              profile_url: 'https://instagram.com/ddoslab'

    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
